# Generated by Django 2.1 on 2020-11-08 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_datetime', models.DateTimeField(auto_now_add=True, verbose_name='전송 일/시간')),
                ('description', models.TextField(blank=True, default='', verbose_name='문의 본문')),
                ('is_checked', models.BooleanField(default=False, verbose_name='확인 여부')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_user', to=settings.AUTH_USER_MODEL, verbose_name='문의자')),
            ],
            options={
                'verbose_name': '문의',
            },
        ),
    ]
