# Generated by Django 2.1 on 2020-11-11 12:00

from django.db import migrations, models
import tools


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_image',
            field=models.ImageField(blank=True, default='account/profile_image/user_default_image.png', upload_to=tools.date_upload_to, verbose_name='프로필 이미지'),
        ),
    ]
