# Generated by Django 2.2 on 2020-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0002_auto_20201111_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mailing_assignment',
            field=models.BooleanField(default=False, verbose_name='이메일 수신 동의'),
        ),
    ]
