# Generated by Django 2.2 on 2020-11-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0004_auto_20201123_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='follwer',
            new_name='follower',
        ),
    ]
