# Generated by Django 2.2 on 2020-12-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0006_customer_kakao_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='kakao_code',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='카카오톡 고유 ID'),
        ),
    ]
