# Generated by Django 2.2 on 2020-12-19 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0007_auto_20201202_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='follower',
        ),
        migrations.AddField(
            model_name='customer',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='팔로잉'),
        ),
    ]
