# Generated by Django 2.2 on 2020-11-14 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='매칭 제목')),
                ('is_matched', models.BooleanField(default=False, verbose_name='성사 여부')),
                ('region', models.CharField(choices=[('R0', '지역'), ('R1', '서울특별시'), ('R2', '부산광역시'), ('R3', '대구광역시'), ('R4', '인천광역시'), ('R5', '광주광역시'), ('R6', '울산광역시'), ('R7', '세종특별자치시'), ('R8', '경기도'), ('R9', '강원도'), ('R10', '충청북도'), ('R11', '충청남도'), ('R12', '경상북도'), ('R13', '경상남도'), ('R14', '제주특별자치도'), ('R15', '전체')], default=('R0', '지역'), max_length=8, verbose_name='지역')),
                ('region_detail', models.CharField(default='', max_length=30, verbose_name='지역 상세 정보')),
                ('tattoo_type', models.CharField(choices=[('T0', '기타'), ('T1', '이레즈미'), ('T2', '블랙앤그레이'), ('T3', '올드스쿨'), ('T4', '뉴스쿨'), ('T5', '뉴재패니즈투'), ('T6', '레터링'), ('T7', '인물타투'), ('T8', '라인워크'), ('T9', '미니타투'), ('T10', '전체')], default=('T0', '기타'), max_length=20, verbose_name='타투 유형')),
                ('part', models.CharField(choices=[('P0', '기타'), ('P1', '머리'), ('P2', '쇄골'), ('P3', '목'), ('P4', '어깨'), ('P5', '가슴'), ('P6', '명치'), ('P7', '옆구리'), ('P8', '배'), ('P9', '윗팔등'), ('P10', '팔등'), ('P11', '팔꿈치'), ('P12', '손등'), ('P13', '손날'), ('P14', '손가락'), ('P15', '무릎'), ('P16', '허벅지'), ('P17', '종아리'), ('P18', '발등'), ('P19', '전체')], default=('P0', '기타'), max_length=20, verbose_name='부위')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('description', models.TextField(blank=True, default='', verbose_name='공고글')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_author_tattooist', to=settings.AUTH_USER_MODEL, verbose_name='매칭 작성자')),
                ('tattoo_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_tatoo_model', to=settings.AUTH_USER_MODEL, verbose_name='타투 모델')),
            ],
            options={
                'verbose_name': '매칭 게시글',
            },
        ),
    ]
