# Generated by Django 2.1 on 2020-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='part',
            field=models.CharField(choices=[('P0', '기타'), ('P1', '머리'), ('P2', '쇄골'), ('P3', '목'), ('P4', '어깨'), ('P5', '가슴'), ('P6', '명치'), ('P7', '옆구리'), ('P8', '배'), ('P9', '윗팔등'), ('P10', '팔등'), ('P11', '팔꿈치'), ('P12', '손등'), ('P13', '손날'), ('P14', '손가락'), ('P15', '무릎'), ('P16', '허벅지'), ('P17', '종아리'), ('P18', '발등'), ('P19', '전체')], default=('P0', '기타'), max_length=20, verbose_name='부위'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='region',
            field=models.CharField(choices=[('R0', '지역'), ('R1', '서울특별시'), ('R2', '부산광역시'), ('R3', '대구광역시'), ('R4', '인천광역시'), ('R5', '광주광역시'), ('R6', '울산광역시'), ('R7', '세종특별자치시'), ('R8', '경기도'), ('R9', '강원도'), ('R10', '충청북도'), ('R11', '충청남도'), ('R12', '경상북도'), ('R13', '경상남도'), ('R14', '제주특별자치도'), ('R15', '전체')], default=('R0', '지역'), max_length=8, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='tattoo_type',
            field=models.CharField(choices=[('T0', '기타'), ('T1', '이레즈미'), ('T2', '블랙앤그레이'), ('T3', '올드스쿨'), ('T4', '뉴스쿨'), ('T5', '뉴재패니즈투'), ('T6', '레터링'), ('T7', '인물타투'), ('T8', '라인워크'), ('T9', '미니타투'), ('T10', '전체')], default=('T0', '기타'), max_length=20, verbose_name='타투 유형'),
        ),
    ]
