# Generated by Django 2.1 on 2020-11-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingApp', '0002_auto_20201111_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='title',
            field=models.CharField(default='noname', max_length=50, verbose_name='매칭 제목'),
            preserve_default=False,
        ),
    ]
