# Generated by Django 2.2 on 2020-11-23 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchingApp', '0003_matching_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='likers',
            field=models.ManyToManyField(related_name='matching_likers', to=settings.AUTH_USER_MODEL, verbose_name='찜한 사용자'),
        ),
    ]
