# Generated by Django 2.2 on 2020-11-30 15:10

from django.db import migrations, models
import tools


class Migration(migrations.Migration):

    dependencies = [
        ('matchingApp', '0006_auto_20201123_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='image',
            field=models.ImageField(blank=True, default='matching/matching_image/default_matching_image.png', upload_to=tools.date_upload_to, verbose_name='매칭 이미지'),
        ),
    ]
