# Generated by Django 2.2 on 2020-11-14 12:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matchingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('review_image', models.ImageField(blank=True, default='tattoistApp/review_image/default_review_image.png', upload_to=tools.date_upload_to, verbose_name='리뷰 사진')),
                ('description', models.TextField(blank=True, default='', verbose_name='리뷰 본문')),
                ('matching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_matching', to='matchingApp.Matching', verbose_name='대상 매칭')),
                ('review_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_review_autor', to=settings.AUTH_USER_MODEL, verbose_name='리뷰 작성자')),
            ],
            options={
                'verbose_name': '리뷰',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.ImageField(upload_to=tools.date_upload_to, verbose_name='포트폴리오 사진')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('description', models.TextField(blank=True, default='', verbose_name='포트폴리오 본문')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_author', to=settings.AUTH_USER_MODEL, verbose_name='포트폴리오 작성자')),
            ],
            options={
                'verbose_name': '포트폴리오',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_datetime', models.DateTimeField(auto_now_add=True, verbose_name='전송 일/시간')),
                ('description', models.TextField(blank=True, default='', verbose_name='메세지 본문')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_customer', to=settings.AUTH_USER_MODEL, verbose_name='메세지 발신자')),
                ('tattooist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_tattooist', to=settings.AUTH_USER_MODEL, verbose_name='메세지 수신자')),
            ],
            options={
                'verbose_name': '메시지',
            },
        ),
    ]
