# Generated by Django 2.1 on 2020-11-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooistApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(upload_to='tattooistApp/profile_image', verbose_name='포트폴리오 사진'),
        ),
    ]
