# Generated by Django 2.1 on 2020-11-11 12:00

from django.db import migrations, models
import tools


class Migration(migrations.Migration):

    dependencies = [
        ('tattooistApp', '0002_auto_20201108_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(upload_to=tools.date_upload_to, verbose_name='포트폴리오 사진'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, default='tattoistApp/review_image/default_review_image.png', upload_to=tools.date_upload_to, verbose_name='리뷰 사진'),
        ),
    ]
