# Generated by Django 2.2 on 2020-12-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattooistApp', '0003_auto_20201111_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='tattooist',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='customer',
            new_name='sender',
        ),
    ]
